let g:ale_cpp_cc_options='`llvm-config --cxxflags --ldflags --system-libs --libs core`'
let g:ale_cpp_clangtidy_options='`llvm-config --cxxflags --ldflags --system-libs --libs core`'
let g:ale_cpp_clangtidy_options='`llvm-config --cxxflags --ldflags --system-libs --libs core`'
let g:ale_cpp_cppcheck_options='`llvm-config --cxxflags --ldflags --system-libs --libs core` --enable=style'
let g:ale_cpp_clangcheck_options='`llvm-config --cxxflags --ldflags --system-libs --libs core`'
let g:ale_cpp_clangd_options='`llvm-config --cxxflags --ldflags --system-libs --libs core`'
