let g:ale_cpp_cc_options='`llvm-config --cxxflags` -Iinclude'
let g:ale_cpp_clangtidy_options='`llvm-config --cxxflags` -Iinclude'
let g:ale_cpp_clangtidy_options='`llvm-config --cxxflags` -Iinclude'
let g:ale_cpp_cppcheck_options='`llvm-config --cxxflags` --enable=style -Iinclude'
let g:ale_cpp_clangcheck_options='`llvm-config --cxxflags` -Iinclude'
let g:ale_cpp_clangd_options='`llvm-config --cxxflags` -Iinclude'
let g:ale_c_cc_options='-std=c11 -Wall `llvm-config --cflags` -Iinclude'
let g:ale_c_clangd_options='`llvm-config --cflags` -Iinclude'
let g:ale_c_clangtidy_options='`llvm-config --cflags` -Iinclude'
let g:ale_c_cppcheck_options='--enable=style `llvm-config --cflags` -Iinclude'
let g:ale_c_flawfinder_options='`llvm-config --cflags` -Iinclude'
